<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'd399e0294694d42591df2fd7e1552835',
  'DATABASE_URL' => 'mysql://root:qHTavO1ajSOnQzUdi3ef@127.0.0.1:3306/bbdgnc?serverVersion=8.0',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
